name: Publish release

on: release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload to release
      uses: JasonEtco/upload-to-release@v0.1.1
      with:
        args: target/tgvmax-auto-confirm-1.2-bin.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
